### ISSUE TITLE
M.2 NVME Drive. No partition detected

### ISSUE THREAD

**Issue by derfo080808** [rescuezilla/rescuezilla#27]
I was trying to back up a laptop with an NVME m.2 drive and no partition appears after selecting the source hard drive. (The drive is detected)

I see all partition on the NVME Drive when it's time to choose the destination drive

If i continue, the progression bar stay stuck a 0% with no estimated time

My controller mode is set to AHCI

![20191203_132513](https://user-images.githubusercontent.com/1361342/70078682-20bfa480-15d1-11ea-854d-45792b986909.jpg)
![20191203_132626](https://user-images.githubusercontent.com/1361342/70078683-20bfa480-15d1-11ea-8fb6-bdad030a39e0.jpg)
![20191203_132547](https://user-images.githubusercontent.com/1361342/70078685-20bfa480-15d1-11ea-8f26-8241af7e8b0b.jpg)

**Comment by robm791** [comment]
A long-time Redo user, with a new M.2 NVMe SSD and Redo doesn't work. Looking for an alternative I found Rescuezilla - Hooray! But  found this same bug - Boo!

In case no-one has sent it, attached is a log from the Rescuezilla session.

It found the disc: nvme0n1 Samsung 970 EVO Plus 500 GB.
It didn't break down the partitions to display them.

There is a second device listed under *** nvmenp *** which lists the M.2 drive's partitions, but they have an added letter p between the device name and the partition number. Not the same pattern as all the other drives. The partition sizes are correct, but the number of bytes are wrong, as per the error messages.

Does this help?
Rob

[rescuezilla.20200111T100545.txt](https://github.com/rescuezilla/rescuezilla/files/4049047/rescuezilla.20200111T100545.txt)

**Comment by shasheene** [comment]
Thank you for the report and the logs. In might be several weeks until a new release. I have been very busy recently but will be spending a bunch of time of Rescuezilla very soon to clear out all the reported bugs and release a v1.0.5.1.

**Comment by ArenT1981** [comment]
Hello

I can also confirm that I get the exact same bug with the 1TB version of the Samsung 970 EVO M2. NVMe drive. Was hoping to use this software to create a cloned disk image backup of my Linux system.

This is a real pity, as this program is potentially brilliant.

I came across this program as Clonezilla has proved worse that useless with me with the latest stable release. Irrespective of what graphics mode I select, after the initial Clonezilla boot screen/menu, every single option ends up going to either a blank screen or just infinite blinking cursor. Even the failsafe VGA mode freezes. It once made it to the login (--nologin) prompt, before freezing there instead. But usually it just creates an infinite blank screen.

By contrast, this booted up first time straight to a graphical desktop, very quickly, and all was good until the first screenshot by @derfo080808 above. Exact same thing; nothing listed on the drive. 

Looking forward to the next release which hopefully fixes this bug and gives us a proper backup solution for modern computers in 2020. 

Thanks for the hard work so far @shasheene. :-)

**Comment by shasheene** [comment]
I have added NVMe support in a change I developed a few weeks ago. Because it made some major changes to the internal workings of the application, it needs a lot of manual testing to make sure nothing has broken since v1.0.4 and v1.0.5, including full backwards compatibility. The actual application has no automated tests yet with my focus being on fixing the existing bug list.

I will try and get my v1.0.5.1 release done in the next 7 days!

**Comment by shasheene** [comment]
OK I have merged the core NVMe support. It will be released with v1.0.5.1 in the next week or so.

With this change, backups can be created from NVMe disks. These backups can be restored to other NVMe disks or SATA/PATA/etc disks, and vice vera. Backwards compatiblity works with backups created with v1.0.4 and v1.0.5 restoring correctly to NVMe drives.

**The only backwards compatibility problem is an NVMe backup cannot be restored with v1.0.5 to a non-NVMe drive as the application tries to process the source partition information.** Actually, thinking about this further, it's probably worth writing false source partition information to the Rescuezilla text file (eg. a file containing 'sda4' rather than 'nvme0n1p4') because this will mean v1.0.5 will then be able to successfully restore an NVMe drive created with v1.0.5.1.

**Comment by shasheene** [comment]
NVMe support has been fully implemented and will be released with v1.0.5.1 in the next week or so. 


Compatibility works how you would expect. For any users having trouble and coming across this thread I'll expand upon this: Backups of NVMe drives made with v1.0.5.1 can be restored using v1.0.5.1 to other NVMe drives and non-NVMe drives. Backups of non-NVMe drives created with v1.0.4 and v1.0.5 restoring correctly to NVMe drives. Backup and restore of NVMe drives continue to be unsupported using v1.0.5. However restoring an NVMe drive backup made with v1.0.5.1 to a non-NVMe drive using v1.0.5 is correctly supported. Finally, restoring a backup made with v1.0.5 or v1.0.5.1 using the 7 year old v1.0.4 release continues to be not supported or recommended due to the internal partclone utility having broken backwards compatibility over that 7 year gap.

**Comment by shasheene** [comment]
@derfo080808, @robm791, @ArenT1981 

[Rescuezilla v1.0.5.1](https://github.com/rescuezilla/rescuezilla/releases/tag/1.0.5.1) supports NVMe drives.

Let me know if you have any issues with Rescuezilla, NVMe-related or otherwise.

**Comment by shasheene** [comment]
@derfo080808, @robm791, @ArenT1981,

Sorry to bother you all, but given you expressed interest in Rescuezilla NVMe support you may be impacted by a [bug in the 32-bit Linux kernel memory allocator](https://bugzilla.kernel.org/show_bug.cgi?id=196157), where **if you have 16GB RAM of greater** your **backup/restore speed will be VERY SLOW unless you press 'tab' at the boot menu and modify the line that pops up so it ends in "quiet mem=10G splash --" instead of "quiet splash --" then press enter**. This bug affects Rescuezilla v1.0.5.1 and v1.0.5.

The next 32-bit Rescuezilla release will run at full speeds on all systems [without](https://github.com/rescuezilla/rescuezilla/issues/15#issuecomment-611541952) the need to modify that line. Also, a [64-bit version of Rescuezilla](https://github.com/rescuezilla/rescuezilla/issues/3) is coming soon.

Once again, let me know if you have any issues with Rescuezilla, NVMe-related or otherwise.

**Comment by billlum** [comment]
Hi, I am using the latest version freshly downloaded, but still have the same problem mentioned above. No visibility of partitions on my ADATA m.2 SSD source drive.

**Comment by shasheene** [comment]
Hi @billlum,

Not seeing partitions listed on an NVMe drive when using Rescuezilla v1.0.5.1 is definitely very strange. Please boot Rescuezilla and reproduce the issue, then collect the log file from rescuezilla.log directory on the desktop and post a comment below with the file uploaded.

**Comment by billlum** [comment]
Thanks @shasheene !

Here's my log file.
[rescuezilla.20200518T133101.txt](https://github.com/rescuezilla/rescuezilla/files/4646547/rescuezilla.20200518T133101.txt)

**Comment by shasheene** [comment]
Hi @billlum,

I have reproduced your issue: Rescuezilla v1.0.5.1 has indeed broken the display of operating system menu entries. Please see #69 for further information.

**Comment by shasheene** [comment]
@derfo080808, @robm791, @ArenT1981,

Sorry to bother you all again (last time I promise). You all may be interested in [Rescuezilla v1.0.6](https://github.com/rescuezilla/rescuezilla/releases/latest) which has now been released, and has some features you may be interested in: a 64-bit version (for machines with greater than 16GB RAM), support of EFI Secure Boot support, and many other improvements.

It definitely worth upgrading. Though the 64-bit version does have a slow shutdown issue that I'm investigating. If you have any issues with Rescuezilla v1.0.6, please let me know.

Also, you may want to know that the original developer of _Redo Backup and Recovery_ has recently [resurfaced after a 7.5 year absence to release an incompatible update named _Redo Rescue_ v2.0.0](https://sourceforge.net/p/redobackup/discussion/1169663/thread/d0e37c4750/). You may be interested in evaluating it. It has many features I am intending on adding for Rescuezilla v1.0.7.
